### ISSUE TITLE
React-three-fiber problem

### ISSUE THREAD

**Issue by yyynnn** [MaciejWWojcik/three-plain-animator#1]
Hi!

Running this class in react-three-fiber results in no animation (no errors)

[https://codesandbox.io/s/cannon-threejs-in-react-three-fiber-c3wyv](https://codesandbox.io/s/cannon-threejs-in-react-three-fiber-c3wyv)

What could the problem be?

**Comment by MaciejWWojcik** [comment]
Hello man :) 
its probably because you don't invoke the animate() method in a loop.

To make animation working the animate() method has to be invoked in an animation loop.
For example something like that:
```
animate(){
    animator.animate();
    requestAnimationFrame(animate);
}
animate();
```

another example of that is in this stackblitz: https://stackblitz.com/edit/plain-animations
at 23-26 lines 

So for your code sth like that should work:
```
function HomerPlane({ position }) {
  // Register box as a physics body with mass
  const texturePath = 'https://i.imgur.com/Oj6RJV9.png'
  animator = new PlainAnimator(new THREE.TextureLoader().load(texturePath), 4, 4, 10, 10)
  const texture = animator.init()
  animator.animate()
  console.log(animator)

  const animate = ( ) => {
    animator.animate();
    requestAnimationFrame(animate)
  }
  animate();

  return (
    <mesh position={position}>
      <planeGeometry attach="geometry" args={[2, 2, 2]} />
      <meshBasicMaterial attach="material" map={texture} />
    </mesh>
  )
}

```

**Comment by yyynnn** [comment]
Thanks!
Great lib!
Yeah even better to bring animate() outside of a component scope, specially when they are mapped

**Comment by MaciejWWojcik** [comment]
Thanks! Glad to hear that 😄 

Yeah - so basically my idea was to bring it outside so to give a developer full control over the animation without any potentials memory leaks due to unclosed animation

**Comment by pollen8** [comment]
from this SO post https://stackoverflow.com/questions/61030786/animated-textures-with-react-three-fibre I think the most idomatic way to do this in r3f is 

```
import { useFrame } from 'react-three-fiber';
useFrame(() => animator.animate());
```

**Comment by MaciejWWojcik** [comment]
Agree. The important thing is to take care of calling `animator.animate()` in a manageable loop :) `useFrame()` seems to do it perfectly
