### ISSUE TITLE
Shader over texture

### ISSUE THREAD

**Issue by yyynnn** [MaciejWWojcik/three-plain-animator#2]
Hi there, Its me again!

Is the a way to put shader over mesh with animator?

e.g. this dither shader -> https://github.com/homeisfar/threejs-dithershader/blob/master/js/shaders/DitherShader.js

Could you please provide the example? 😊 

The method i do now just merges shader color with the texture but texture itself became a static png strip as it is

**Comment by MaciejWWojcik** [comment]
Hey man! 
Good question, I will think about it and provide some example 😃 

no worries, I just need some time for that

**Comment by yyynnn** [comment]
I think it will be much easier to just create some shader that animates a png sprite)
So this is out of the scope of this lib

**Comment by MaciejWWojcik** [comment]
yup, so I tried to add some shader but I cannot find any pleasant solution for that :(
